import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import QueryProvider from "./providers/QueryProvider";


export const metadata: Metadata = {
  title: "mohammedAlareer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-900">
      <QueryProvider>
      <Navbar/>
      <main className="">
        {children}
        </main>
        </QueryProvider>
        </body>
    </html>
  );
}
